" No comapatible mode
set nocompatible

" Add line numbers
set number

set encoding=utf-8

" Useful Features
set autoindent
set smarttab
set incsearch
set hlsearch
set scrolloff=5
set sidescrolloff=5
set autoread
set tabstop=8 softtabstop=0 expandtab shiftwidth=4 smarttab

" Obscure features
set display+=lastline
set clipboard=unnamedplus

" Status bar stuff
set laststatus=2
set showcmd
set ruler
set wildmenu

execute "set <M-u>=\eu"
execute "set <M-/>=\e/"
execute "set <M-'>=\e'"

" Key Bindings
nmap <Space> <Leader>
nmap <Leader>p "+p

" Escape key bindings
inoremap kj <Esc>
vnoremap kj <Esc>

" Window key bindings
nmap ,w <C-W>
nmap ,ww <C-W><C-W>
tmap ,ww <C-W><C-W>
tmap ,w <C-W>

" Command key bindings
nmap ,s :w<Enter>
nmap ,q :q<Enter>
tmap ,q exit<Enter>
nmap <M-u> :NERDTreeToggle<Enter>
nmap <M-'> :term<Enter>
nmap <M-/> :noh<Enter>

" Call the .vimrc.plug file
if filereadable(expand("~/.vimrc.plug"))
    source ~/.vimrc.plug
endif

" theme
syntax enable
set background=dark
let g:gruvbox_italicize_strings = 0
colorscheme gruvbox8
let g:airline_theme = 'gruvbox8d'
let g:airline_powerline_fonts = 0
let g:highlightedyank_highlight_duration = 300


if !exists('g:airline_symbols')
    let g:airline_symbols={}
endif

" airline symbols
let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''
let g:airline_symbols.branch = ''
let g:airline_symbols.readonly = ''
let g:airline_symbols.linenr = ''

" unicode symbols
let g:airline_left_sep = '»'
let g:airline_left_sep = '▶'
let g:airline_right_sep = '«'
let g:airline_right_sep = '◀'
let g:airline_symbols.linenr = '␊'
let g:airline_symbols.linenr = '␤'
let g:airline_symbols.linenr = '¶'
let g:airline_symbols.branch = '⎇'
let g:airline_symbols.paste = 'ρ'
let g:airline_symbols.paste = 'Þ'
let g:airline_symbols.paste = '∥'
let g:airline_symbols.whitespace = 'Ξ'

let g:lightline = {'separator': { 'left': '', 'right': '' },'subseparator': { 'left': '', 'right': '' }}

let g:EditorConfig_exclude_patterns = ['fugitive://.*']

set viminfofile+=~/dotfiles/vim/viminfo
