#!/bin/bash

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

export AWT_TOOLKIT=MToolkit

# merge in defaults and keymaps

if [ -f $sysresources ]; then







    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then







    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Monitor handling
default_name="eDP1"
default_size="1920x1080"

readarray -t monitor_data <<< "$(xrandr --listmonitors)"
unset "monitor_data[0]"
monitor_count=${#monitor_data[@]}

if [ "$monitor_count" -gt 1 ]; then
  for monitor in "${monitor_data[@]}"; do
    monitor_name=${monitor##* }
    if [ "$monitor_name" = "$default_name" ]; then
      xrandr --output "$default_name" --mode "$default_size"
      xrandr --output "$default_name" --off
    fi
  done
else
  xrandr --output "$default_name" --mode "$default_size"
fi

picom -f &
setxkbmap gb &
nitrogen --restore &

exec bspwm
